defmodule TcpTest.Application do
  require Logger

  use Application

  def start(_type, _args) do
    Logger.configure(truncate: :infinity)
    opts = [strategy: :one_for_one, name: TcpTest.Supervisor]
    Supervisor.start_link(children(), opts)
  end

  def stop(_state), do: Logger.info("Application shutdown gracefully")

  def children() do
    [
      {TcpTest.LineReverse.Supervisor, String.to_integer(System.get_env("TCP_PORT") || "5001")}
    ]
  end
end

%{
  900 =>
    "le something calculator the for sphinx love peach good love giant something to royale PROTOHACKERS nasa the hypnotic is now casino quartz is prisoners giant is calculator to quartz my of casino royale prisoners party quartz giant of the for sphinx time the to something good men the about the the of something love bluebell PROTOHACKERS integral intrusion bluebell party giant my PROTOHACKERS good royale all the to party giant PROTOHACKERS my something to of time my of PROTOHACKERS of the of the time to of bluebell peach sphinx the favicon favicon good favicon giant intrusion favicon prisoners giant the love peach my of intrusion men party prisoners royale is of quartz something the is party royale aid now something of now love peach royale hypnotic all giant aid prisoners intrusion time royale casino royale quartz giant all giant now come to giant the to hypnotic bluebell peach casino men ",
  1800 =>
    "to royale sphinx PROTOHACKERS casino casino giant the men now love something for for for giant the good of time bluebell jackdaws of giant my jackdaws about the good integral intrusion giant intrusion favicon of PROTOHACKERS time come peach hypnotic intrusion integral the favicon is integral come of now now come bluebell casino my time jackdaws about bluebell royale sphinx casino to the prisoners royale the integral casino hypnotic prisoners sphinx aid hypnotic peach for party bluebell aid prisoners my quartz for aid the all intrusion intrusion PROTOHACKERS is party bluebell peach all the PROTOHACKERS men sphinx to giant giant bluebell the come peach prisoners calculator sphinx love bluebell PROTOHACKERS hypnotic quartz calculator to calculator intrusion hypnotic now is of men sphinx royale favicon sphinx party sphinx PROTOHACKERS giant intrusion sphinx prisoners all prisoners casino tim",
  3600 =>
    "ale aid royale for time peach of party calculator hypnotic integral party hypnotic men for intrusion of love time giant about giant my now peach about something of come all of jackdaws favicon giant nasa love my all giant favicon party favicon the bluebell for the casino giant nasa good good my love of favicon prisoners men sphinx aid my is good the calculator of men to bluebell my my bluebell giant time jackdaws men jackdaws sphinx something of quartz something hypnotic of favicon hypnotic the integral party hypnotic the prisoners hypnotic integral to about is casino come of integral jackdaws about good hypnotic all love all peach hypnotic peach quartz PROTOHACKERS PROTOHACKERS the PROTOHACKERS all giant come quartz hypnotic giant jackdaws peach aid jackdaws to is time the love men party PROTOHACKERS quartz calculator of my the to for something PROTOHACKERS jackdaws party come of sphinx",
  4500 =>
    " come integral good nasa to casino aid love integral giant to giant giant prisoners bluebell about something party about for bluebell casino integral my nasa my nasa love the casino love party royale royale of calculator my to about good for my the about giant something nasa giant now integral intrusion favicon nasa intrusion aid calculator sphinx favicon to to party of all the love to of men now PROTOHACKERS hypnotic about royale royale party to the giant peach my calculator favicon jackdaws come now\nPROTOHACKERS giant giant good casino royale time my my nasa of intrusion all now casino calculator favicon for party quartz bluebell to come men for prisoners sphinx men royale about my hypnotic hypnotic casino now come aid now my my hypnotic the is aid favicon royale bluebell come about royale sphinx good to bluebell to all giant of all to royale intrusion quartz favicon jackdaws for come ",
  8100 =>
    "party to all about love to all party sphinx party the love jackdaws quartz for now my PROTOHACKERS my to intrusion favicon intrusion now nasa jackdaws all the good casino hypnotic quartz is quartz men casino party about peach calculator of men integral to all giant giant men time my time bluebell to now all favicon calculator casino now come giant is love jackdaws hypnotic the all time giant is hypnotic time giant something intrusion giant about for jackdaws intrusion prisoners men hypnotic about peach men intrusion all men giant giant hypnotic of time PROTOHACKERS for is for party to good now about my of integral the prisoners something PROTOHACKERS intrusion my integral prisoners prisoners for bluebell to men party sphinx of quartz of good party hypnotic intrusion the of favicon something of intrusion the men now peach something intrusion for time time for come something the nasa royal",
  9000 =>
    "e peach something of good party royale bluebell hypnotic giant intrusion party of of come something time now intrusion giant quartz PROTOHACKERS of calculator casino PROTOHACKERS for intrusion prisoners giant of giant good quartz jackdaws love favicon for giant the about intrusion for favicon aid integral time jackdaws bluebell time sphinx nasa is nasa casino of the all come the aid the the of time PROTOHACKERS is to quartz nasa bluebell the the bluebell PROTOHACKERS love quartz to favicon the come of of love calculator of time good calculator of aid quartz peach integral love hypnotic hypnotic prisoners PROTOHACKERS integral time sphinx of the intrusion for favicon time hypnotic the men nasa of all hypnotic bluebell about for about something my the come favicon something jackdaws aid men about peach for of now hypnotic integral jackdaws giant hypnotic nasa integral calculator PROTOHACKE",
  11700 =>
    " the of quartz the the aid is favicon something calculator intrusion love about all intrusion sphinx for is of now royale all time the hypnotic favicon peach of love quartz is come of casino to good for of of integral of integral now aid casino good royale something to jackdaws for love bluebell calculator of is good to calculator something bluebell sphinx about peach giant peach men now giant giant giant love is for PROTOHACKERS hypnotic quartz the sphinx for something royale of my intrusion is PROTOHACKERS for hypnotic giant prisoners peach giant jackdaws the of for the integral integral now giant PROTOHACKERS men favicon intrusion the the hypnotic calculator peach my casino sphinx quartz my casino royale is time to now sphinx calculator for all integral royale sphinx for sphinx for love prisoners about for quartz for aid jackdaws to party to quartz prisoners jackdaws for is now someth",
  12600 =>
    "ing all aid the for of sphinx good men come giant good time to prisoners favicon all sphinx quartz now my for the for royale prisoners of hypnotic aid now hypnotic bluebell the something something party sphinx come giant bluebell favicon something time integral to now of about giant is men now prisoners sphinx the good to about giant favicon men calculator giant bluebell sphinx of come for of love to PROTOHACKERS favicon aid the all something PROTOHACKERS now to the calculator is hypnotic for peach sphinx jackdaws my now something for good casino peach PROTOHACKERS giant now nasa men prisoners integral men time about intrusion the the casino time jackdaws of party aid peach giant of come intrusion good prisoners love royale now prisoners men my now about something for about integral casino about nasa quartz aid is nasa for casino PROTOHACKERS love for the of quartz favicon prisoners PROT",
  13500 =>
    "OHACKERS of intrusion love something about jackdaws aid hypnotic now all time prisoners come intrusion bluebell party for now something now the intrusion for giant peach giant of of party party prisoners all come integral of my to calculator royale my bluebell of intrusion PROTOHACKERS my men giant favicon giant of now time prisoners intrusion intrusion bluebell come intrusion now favicon men quartz something PROTOHACKERS royale sphinx intrusion for to hypnotic now the good for nasa calculator about bluebell to calculator for intrusion come my all of PROTOHACKERS now to sphinx giant the peach quartz something royale sphinx of calculator something about time the now my bluebell sphinx now good integral hypnotic is giant men nasa casino about something aid integral hypnotic for integral of the hypnotic prisoners my now men come to jackdaws for bluebell the PROTOHACKERS quartz peach now pea",
  15300 =>
    "r casino quartz is bluebell giant sphinx is giant calculator integral the peach calculator PROTOHACKERS now of party party bluebell the the something good to calculator the calculator peach PROTOHACKERS the peach to PROTOHACKERS men nasa calculator sphinx PROTOHACKERS good integral about for party intrusion to come time for is my the time about of bluebell good favicon all for of aid intrusion casino giant of nasa about of sphinx love peach to something for come jackdaws calculator the PROTOHACKERS good for my jackdaws party all prisoners giant the aid prisoners sphinx favicon party giant PROTOHACKERS jackdaws all hypnotic nasa time jackdaws is my the bluebell the aid the bluebell casino intrusion of the my the party hypnotic giant peach the men aid come prisoners sphinx hypnotic calculator giant hypnotic is jackdaws of for for PROTOHACKERS men nasa good good my something PROTOHACKERS gi",
  29700 =>
    "out now favicon the bluebell to aid the the for love bluebell jackdaws the the quartz integral the sphinx sphinx to for men party love prisoners prisoners time to to love royale prisoners peach something giant PROTOHACKERS party about come the to of time prisoners giant sphinx time about my sphinx love about all giant now casino party men casino for love intrusion about quartz jackdaws time time PROTOHACKERS nasa intrusion now intrusion about favicon casino good bluebell of all for intrusion for the aid my men now time nasa\nnasa peach hypnotic PROTOHACKERS calculator something my come party about royale aid come giant royale party calculator for for is giant jackdaws the men love quartz the giant is to of men to bluebell party giant all men peach my PROTOHACKERS men intrusion of aid PROTOHACKERS the peach time for of calculator calculator to aid now something giant the the for good for t",
  31500 =>
    "lator bluebell of giant men jackdaws calculator of the giant giant jackdaws love of hypnotic favicon love for integral sphinx my good of peach prisoners giant peach good giant of for intrusion now giant the of about giant of the love aid about bluebell about good about giant the sphinx bluebell sphinx to something PROTOHACKERS the intrusion of is party jackdaws come quartz the bluebell of to aid giant peach peach all the quartz about men come come giant jackdaws my peach to bluebell hypnotic is love to about good casino calculator of the all men aid love now hypnotic the nasa all men now favicon time men to come about is love nasa my for the good favicon favicon prisoners to good about the party giant of hypnotic integral to about nasa integral about good favicon for is for to favicon royale to to to of about to casino integral for intrusion men my integral giant the all giant casino pri",
  33300 =>
    "sino for of bluebell my men about jackdaws to the for my something time prisoners peach love for casino aid intrusion royale my bluebell integral quartz my peach all giant quartz nasa love for all integral nasa integral the to to calculator the sphinx the men aid party royale of to is good something all sphinx favicon nasa prisoners hypnotic giant is party men nasa of jackdaws giant bluebell the now the for something sphinx bluebell peach bluebell giant for now of come hypnotic favicon of aid favicon love all all intrusion prisoners PROTOHACKERS something casino quartz prisoners prisoners royale come of calculator nasa for PROTOHACKERS my party giant giant quartz PROTOHACKERS about men hypnotic about now to the royale for sphinx is the jackdaws of the for royale something peach my of men the jackdaws for the good about favicon time for to favicon quartz men for giant favicon of the giant",
  35100 =>
    "le giant my come come the something my party integral peach hypnotic come calculator aid is men of come for royale giant peach for\nnow men favicon quartz time calculator giant men the sphinx calculator calculator to my for intrusion intrusion of integral giant to for for royale favicon bluebell to my royale the casino calculator peach favicon about now hypnotic prisoners sphinx jackdaws something peach sphinx calculator peach sphinx prisoners of intrusion intrusion for nasa giant royale is the royale integral PROTOHACKERS giant party casino to my bluebell sphinx time men the of intrusion bluebell aid PROTOHACKERS of time aid intrusion the prisoners to casino intrusion royale nasa about time my to to something for giant of giant sphinx to giant men my hypnotic prisoners hypnotic to to about is of love love to the prisoners jackdaws aid of casino royale party prisoners intrusion something ",
  36900 =>
    " for prisoners my royale casino come calculator royale nasa about jackdaws sphinx about sphinx sphinx prisoners of about party party love of integral the good royale casino casino PROTOHACKERS something giant party the for peach for to giant PROTOHACKERS intrusion come hypnotic hypnotic hypnotic the giant for favicon intrusion nasa peach love the casino intrusion bluebell of good giant aid something men of calculator men integral peach aid sphinx my bluebell to of favicon time my giant the intrusion giant something giant the party of my about the the time royale hypnotic all sphinx now the for about peach the to hypnotic for peach integral to integral royale jackdaws for integral time of the now time favicon calculator intrusion for for the giant come of integral good love love bluebell now bluebell calculator intrusion intrusion love giant of integral of calculator now something the int",
  37800 =>
    "rusion something something calculator nasa men good jackdaws quartz giant is the PROTOHACKERS of of the the now time party party royale something the is aid bluebell all peach for the good giant for quartz now quartz the intrusion about party favicon love men about sphinx the my integral sphinx intrusion integral favicon good hypnotic for party intrusion intrusion favicon the for casino the the my men good my aid casino the for intrusion aid peach calculator hypnotic something time nasa calculator hypnotic nasa sphinx quartz good intrusion nasa prisoners sphinx quartz all to time the time good party party aid PROTOHACKERS is my now for good casino favicon intrusion giant royale come to giant sphinx time men all come something hypnotic party come all is for come giant is all time the the favicon all prisoners for giant time PROTOHACKERS about favicon come aid of the integral now hypnotic ",
  44100 =>
    " men come come the favicon royale calculator prisoners prisoners royale hypnotic royale party nasa to men sphinx giant nasa PROTOHACKERS for giant all aid quartz men sphinx peach quartz for men for bluebell favicon to nasa integral giant hypnotic for royale intrusion intrusion peach royale of prisoners casino PROTOHACKERS bluebell something about royale come prisoners favicon sphinx something peach giant time aid sphinx about love party jackdaws to peach come prisoners something time giant the aid for is now time for come nasa bluebell aid giant is good about for prisoners all casino time PROTOHACKERS nasa favicon is the time time calculator integral giant now party men sphinx bluebell all is casino giant bluebell to now casino about PROTOHACKERS PROTOHACKERS royale aid for the about the intrusion jackdaws sphinx the the peach nasa my time to men quartz hypnotic good the casino good is s",
  45900 =>
    "gral about for casino my nasa quartz to calculator something come jackdaws giant come sphinx for bluebell giant aid PROTOHACKERS the for PROTOHACKERS royale quartz intrusion come sphinx to for giant party PROTOHACKERS giant for quartz love come prisoners royale calculator jackdaws something for giant is good PROTOHACKERS to sphinx royale something peach now for of sphinx aid the all the for all of intrusion good of something calculator now casino sphinx quartz to for peach giant party bluebell prisoners for is nasa to men the come calculator is the something about PROTOHACKERS PROTOHACKERS party to about prisoners jackdaws quartz PROTOHACKERS all quartz party time good to PROTOHACKERS aid the sphinx integral time peach hypnotic to time peach sphinx come calculator for now the now giant love the quartz love come PROTOHACKERS of giant the nasa favicon time is the of nasa time calculator na",
  46800 =>
    "sa for the the to party time hypnotic royale all all love jackdaws is party is casino something party now giant of come hypnotic time men something of men now prisoners now to of integral aid to sphinx the love to all is my the of nasa favicon calculator to good now nasa about peach to about the now the intrusion to something all of bluebell time of jackdaws men the good men of favicon quartz prisoners integral bluebell sphinx prisoners come aid of giant bluebell sphinx for men about the party aid is all love quartz calculator calculator prisoners sphinx sphinx about for jackdaws time for jackdaws party intrusion men love now integral something PROTOHACKERS quartz hypnotic something all bluebell for royale love jackdaws love of quartz now to the time giant to is all aid all is the hypnotic time good favicon to of to the something PROTOHACKERS my all jackdaws the sphinx giant nasa of all ",
  49500 =>
    "or calculator sphinx the my the something something jackdaws party favicon PROTOHACKERS calculator PROTOHACKERS now love calculator to jackdaws intrusion party about of PROTOHACKERS of to prisoners peach giant giant the aid to something giant casino is nasa casino is party men intrusion PROTOHACKERS of now is party the giant intrusion come calculator good party giant come bluebell for good about bluebell prisoners come intrusion hypnotic men intrusion for intrusion nasa men intrusion casino peach sphinx nasa giant peach royale calculator calculator party men PROTOHACKERS the giant giant giant all the the something bluebell about to to come nasa hypnotic love something quartz now for something men the is good aid casino sphinx come to casino intrusion about for sphinx party bluebell prisoners the the favicon bluebell all party now\n"
}
